version: "3.2"

services:
    django-server:
        command: /bin/sh -c "docker/wait-for-it.sh -t 90 $$POSTGRES_HOST:5432 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        env_file:
            - env/dev.env
        depends_on:
            - postgres
            - celery_worker

    celery_worker:
        env_file:
            - env/dev.env
        depends_on:
            - rabbitmq
            - postgres

    postgres:
        env_file:
            - env/dev.env

    rabbitmq:
        env_file:
            - env/dev.env
