version: "3.2"

services:
    django-server:
        command: /bin/sh -c "docker/wait-for-it.sh -t 90 $$POSTGRES_HOST:5432 && python manage.py migrate && ./e2e/server_with_testdata_postgres.sh"
        environment:
            - DJANGO_SETTINGS_MODULE=exam_tools.settings_compilation_testing
    celery_worker:
        environment:
            - DJANGO_SETTINGS_MODULE=exam_tools.settings_compilation_testing


    testing_cypress:
        depends_on:
            - django-server
        environment:
            - ELECTRON_EXTRA_LAUNCH_ARGS=--js-flags=--expose_gc
        command: ./cypress_pdf_compilation.sh
        ipc: host
        shm_size: '4gb'
