# Generated by Django 3.1.2 on 2020-10-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compiledfigure",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="figure",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="rawfigure",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="compiledfigure",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="rawfigure",
            managers=[],
        ),
    ]
