# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='org_comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='qml_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('V', 'Scheduled for voting'), ('I', 'Implemented'), ('T', 'Settled after voting'), ('W', 'Withdrawn')], default='S', max_length=1),
        ),
    ]
