# Generated by Django 3.1.3 on 2020-11-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0002_auto_20201027_1229"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="can_translate",
            field=models.IntegerField(
                choices=[
                    (-1, "Nobody"),
                    (0, "Organizer only"),
                    (1, "Boardmeeting members"),
                ],
                default=-1,
                help_text="Sets the ability to translate for organizers and delegations.",
                verbose_name="Can Translate",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="delegation_scan_access",
            field=models.IntegerField(
                choices=[(-1, "No"), (0, "Student answer")],
                default=-1,
                help_text="Sets the access to the scanned exams for delegations.",
                verbose_name="Delegation Scan Access",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="feedback",
            field=models.IntegerField(
                choices=[(-1, "Read only"), (0, "Can be opened"), (1, "Invisible")],
                default=-1,
                help_text="Sets the status of the feedbacks for all questions.",
                verbose_name="Feedback",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="marking",
            field=models.IntegerField(
                choices=[
                    (-1, "Not open"),
                    (0, "Organizer only"),
                    (1, "Organizer done, delegation can submit"),
                ],
                default=-1,
                help_text="Allow access to moderation interface.",
                verbose_name="Moderation",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="printing",
            field=models.IntegerField(
                choices=[(-1, "No, not visible"), (0, "When submitted")],
                default=-1,
                help_text="Sets the ability to print the exam.",
                verbose_name="Exam Printing",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="scanning",
            field=models.IntegerField(
                choices=[(-1, "Not possible"), (0, "Student answer")],
                default=-1,
                help_text="Sets the ability for scans being uploaded.",
                verbose_name="Exam Scanning",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="visibility",
            field=models.IntegerField(
                choices=[
                    (-1, "Superuser only"),
                    (0, "Organizer only"),
                    (1, "Boardmeeting members"),
                ],
                default=0,
                help_text="Sets the visibility of the exam for organizers and delegations.",
                verbose_name="Exam Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="hidden",
            field=models.BooleanField(
                default=False, help_text="Exam is viewable for non superusers."
            ),
        ),
    ]
