# Generated by Django 1.11.20 on 2019-06-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0002_auto_20190406_1503"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="with_question",
            field=models.BooleanField(
                default=True, help_text="Deliver question sheets."
            ),
        ),
    ]
