# Generated by Django 1.11.29 on 2020-07-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0002_auto_20190406_1503"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="show_delegation_submissions",
            field=models.BooleanField(
                default=False, help_text="Show submissions of the delegation"
            ),
        ),
    ]
