# Generated by Django 1.11.20 on 2019-07-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0003_studentsubmission_with_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedAutoTranslation",
            fields=[
                (
                    "source_and_lang_hash",
                    models.BinaryField(
                        max_length=16, primary_key=True, serialize=False
                    ),
                ),
                ("source_length", models.IntegerField()),
                ("source_lang", models.CharField(max_length=5)),
                ("target_lang", models.CharField(max_length=5)),
                ("target_text", models.TextField(blank=True)),
                ("hits", models.IntegerField(default=1)),
            ],
        ),
    ]
