# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0003_studentsubmission_with_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('V', 'Scheduled for voting'), ('I', 'Implemented'), ('R', 'Rejected'), ('T', 'Settled after voting'), ('W', 'Withdrawn')], default='S', max_length=1),
        ),
    ]
