# Generated by Django 3.1.3 on 2020-11-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0003_auto_20201103_2323"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="feedback_active",
        ),
        migrations.AddField(
            model_name="question",
            name="feedback_status",
            field=models.IntegerField(
                choices=[
                    ("Closed", -1),
                    ("Open", 1),
                    ("Closed, Organizer can still comment.", 0),
                ],
                default=0,
                help_text="Sets the status of the feedbacks for this questions.",
                verbose_name="Feedback",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="feedback",
            field=models.IntegerField(
                choices=[(0, "Read only"), (1, "Can be opened"), (-1, "Invisible")],
                default=0,
                help_text="Sets the status of the feedbacks for all questions.",
                verbose_name="Feedback",
            ),
        ),
    ]
