# Generated by Django 3.1.3 on 2020-11-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0004_auto_20201104_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="feedback_status",
            field=models.IntegerField(
                choices=[
                    (-1, "Closed"),
                    (1, "Open"),
                    (0, "Closed, Organizer can still comment."),
                ],
                default=-1,
                help_text="Sets the status of the feedbacks for this questions.",
                verbose_name="Feedback",
            ),
        ),
    ]
