# Generated by Django 1.11.20 on 2019-07-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0004_cachedautotranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedautotranslation",
            name="source_and_lang_hash",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
