# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0003_exam_show_delegation_submissions'),
        ('ipho_exam', '0005_auto_20190711_2244'),
    ]

    operations = [
    ]
