# Generated by Django 3.1.3 on 2020-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0007_auto_20201105_1041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="marking",
            field=models.IntegerField(
                choices=[
                    (-1, "Not open"),
                    (0, "Organizer only"),
                    (1, "Organizer done, delegation can submit and sign off"),
                ],
                default=-1,
                help_text="Sets the ability to enter marks for organizers and delegations.",
                verbose_name="Marking",
            ),
        ),
    ]
