# Generated by Django 3.1.3 on 2020-11-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0008_auto_20201105_1159"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="active",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="hidden",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="hide_feedback",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="marking_active",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="moderation_active",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="show_delegation_submissions",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="show_scans",
        ),
    ]
