# Generated by Django 3.1.2 on 2020-11-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0009_auto_20201105_1259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="visibility",
            field=models.IntegerField(
                choices=[
                    (-1, "2nd level support only"),
                    (0, "Organizer + 2nd level support"),
                    (1, "Boardmeeting + Organizer + 2nd level support"),
                ],
                default=0,
                help_text="Sets the visibility of the exam for organizers and delegations.",
                verbose_name="Exam Visibility",
            ),
        ),
    ]
