# Generated by Django 3.1.2 on 2020-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0010_auto_20201110_1800"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="printing",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="scanning",
        ),
        migrations.AddField(
            model_name="exam",
            name="answer_sheet_scanning",
            field=models.IntegerField(
                choices=[(-1, "Not possible"), (0, "Student answer")],
                default=-1,
                help_text="Sets the ability for scans being uploaded.",
                verbose_name="Answer Sheet Scanning",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="submission_printing",
            field=models.IntegerField(
                choices=[(-1, "No, not visible"), (0, "When submitted")],
                default=-1,
                help_text="Sets the ability to print the exam.",
                verbose_name="Submission Printing",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="can_translate",
            field=models.IntegerField(
                choices=[
                    (-1, "Nobody"),
                    (0, "Organizer only"),
                    (1, "Boardmeeting members and organizers"),
                ],
                default=-1,
                help_text="Sets the ability to translate for organizers and delegations.",
                verbose_name="Can Translate",
            ),
        ),
    ]
