# Generated by Django 3.1.2 on 2020-11-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0011_auto_20201110_1810"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="marking_delegation_action",
            field=models.IntegerField(
                choices=[
                    (-1, "Nothing"),
                    (0, "Can enter and submit marks"),
                    (1, "Can enter, submit and finalize marks"),
                ],
                default=-1,
                help_text="Sets the ability of delegations to enter, submit and finalize their marks.",
                verbose_name="Delegation marking actions",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="marking_delegation_can_see_organizer_marks",
            field=models.IntegerField(
                choices=[
                    (-1, "No"),
                    (0, "When the delegation has submitted their marks"),
                    (1, "Yes"),
                ],
                default=-1,
                help_text="Sets the access of delegations to the organizer marks",
                verbose_name="Delegations can see organizer marks",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="marking_organizer_can_enter",
            field=models.IntegerField(
                choices=[
                    (-1, "No"),
                    (0, "If delegation has not submitted marks"),
                    (1, "If marks are not finalized"),
                ],
                default=-1,
                help_text="Sets the ability of markers to edit marks.",
                verbose_name="Organizers can edit marks",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="marking_organizer_can_see_delegation_marks",
            field=models.IntegerField(
                choices=[
                    (-1, "In moderation and when marks are finalized"),
                    (0, "When the delegation has submitted their marks"),
                ],
                default=-1,
                help_text="Sets the access of organizers to the delegation marks",
                verbose_name="Organizer can see delegation marks",
            ),
        ),
    ]
