# Generated by Django 3.1.3 on 2020-11-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0012_auto_20201110_2111"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="marking",
        ),
    ]
