# Generated by Django 3.1.3 on 2020-11-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0013_remove_exam_marking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="answer_sheet_scanning",
        ),
        migrations.AddField(
            model_name="exam",
            name="answer_sheet_scan_upload",
            field=models.IntegerField(
                choices=[(-1, "Not possible"), (0, "Student answer")],
                default=-1,
                help_text="Sets the ability for scans being uploaded via the web interface.",
                verbose_name="Answer Sheet Manual Scan Upload",
            ),
        ),
    ]
