# Generated by Django 3.1.3 on 2020-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0014_auto_20201113_1951"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="can_translate",
            field=models.IntegerField(
                choices=[
                    (-1, "Nobody"),
                    (0, "Organizer only"),
                    (1, "Boardmeeting members + organizers"),
                ],
                default=-1,
                help_text="Sets the ability to translate for organizers and delegations.",
                verbose_name="Can Translate",
            ),
        ),
    ]
