# Generated by Django 3.1.3 on 2021-02-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0006_auto_20201123_2133"),
        ("ipho_exam", "0015_auto_20201119_1911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="answer_sheet_scan_upload",
            field=models.IntegerField(
                choices=[(-1, "Not possible"), (0, "Participant answer")],
                default=-1,
                help_text="Sets the ability for scans being uploaded via the web interface.",
                verbose_name="Answer Sheet Manual Scan Upload",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="delegation_scan_access",
            field=models.IntegerField(
                choices=[(-1, "No"), (0, "Participant answer")],
                default=-1,
                help_text="Sets the access to the scanned exams for delegations.",
                verbose_name="Delegation Scan Access",
            ),
        ),
        migrations.RenameModel(
            old_name="StudentSubmission",
            new_name="ParticipantSubmission",
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                (
                    "delegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_core.delegation",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="participant",
            field=models.ForeignKey(
                default=None,
                help_text="Participant",
                on_delete=django.db.models.deletion.CASCADE,
                to="ipho_exam.participant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participantsubmission",
            name="participant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="ipho_exam.participant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place",
            name="participant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="ipho_exam.participant",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("exam", "participant", "position")},
        ),
        migrations.AlterUniqueTogether(
            name="participantsubmission",
            unique_together={("participant", "exam", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="place",
            unique_together={("participant", "exam")},
        ),
        migrations.AlterIndexTogether(
            name="document",
            index_together={("exam", "participant", "position")},
        ),
        migrations.AlterIndexTogether(
            name="participantsubmission",
            index_together={("participant", "exam", "language")},
        ),
        migrations.AlterIndexTogether(
            name="place",
            index_together={("participant", "exam")},
        ),
        migrations.RemoveField(
            model_name="document",
            name="student",
        ),
        migrations.RemoveField(
            model_name="participantsubmission",
            name="student",
        ),
        migrations.RemoveField(
            model_name="place",
            name="student",
        ),
    ]
