# Generated by Django 3.1.3 on 2021-02-08 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0007_auto_20210208_2247"),
        ("ipho_exam", "0015_auto_20201119_1911"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentSubmission",
            new_name="ParticipantSubmission",
        ),
        migrations.AlterField(
            model_name="document",
            name="student",
            field=models.ForeignKey(
                help_text="Participant",
                on_delete=django.db.models.deletion.CASCADE,
                to="ipho_core.participant",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="answer_sheet_scan_upload",
            field=models.IntegerField(
                choices=[(-1, "Not possible"), (0, "Participant answer")],
                default=-1,
                help_text="Sets the ability for scans being uploaded via the web interface.",
                verbose_name="Answer Sheet Manual Scan Upload",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="delegation_scan_access",
            field=models.IntegerField(
                choices=[(-1, "No"), (0, "Participant answer")],
                default=-1,
                help_text="Sets the access to the scanned exams for delegations.",
                verbose_name="Delegation Scan Access",
            ),
        ),
    ]
