# Generated by Django 3.1.3 on 2021-02-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0007_auto_20210208_2247"),
        ("ipho_exam", "0016_auto_20210208_2305"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="student",
            new_name="participant",
        ),
        migrations.RenameField(
            model_name="participantsubmission",
            old_name="student",
            new_name="participant",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="student",
            new_name="participant",
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("exam", "participant", "position")},
        ),
        migrations.AlterUniqueTogether(
            name="participantsubmission",
            unique_together={("participant", "exam", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="place",
            unique_together={("participant", "exam")},
        ),
        migrations.AlterIndexTogether(
            name="document",
            index_together={("exam", "participant", "position")},
        ),
        migrations.AlterIndexTogether(
            name="participantsubmission",
            index_together={("participant", "exam", "language")},
        ),
        migrations.AlterIndexTogether(
            name="place",
            index_together={("participant", "exam")},
        ),
    ]
