# Generated by Django 3.1.2 on 2021-07-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0017_auto_20210612_2203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="scan_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Printed"),
                    ("S", "Success"),
                    ("W", "Warning"),
                    ("M", "Missing pages"),
                ],
                help_text="Status of the scanned document. P - Printed, S - Success, W - Warning, M - Missing pages",
                max_length=10,
                null=True,
            ),
        ),
    ]
