# Generated by Django 3.1.3 on 2021-02-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0008_auto_20210218_1159"),
        ("ipho_exam", "0017_auto_20210208_2315"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                (
                    "delegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_core.delegation",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="participant",
            field=models.ForeignKey(
                help_text="Participant",
                on_delete=django.db.models.deletion.CASCADE,
                to="ipho_exam.participant",
            ),
        ),
        migrations.AlterField(
            model_name="participantsubmission",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ipho_exam.participant"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ipho_exam.participant"
            ),
        ),
    ]
