# Generated by Django 3.1.3 on 2021-02-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0017_auto_20210220_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="exam",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="ipho_exam.exam",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="participant",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("code", "exam")},
        ),
        migrations.AlterIndexTogether(
            name="participant",
            index_together={("code", "exam")},
        ),
    ]
