# Generated by Django 3.1.3 on 2021-02-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0019_participant_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="is_group",
            field=models.BooleanField(default=False),
        ),
    ]
