# Generated by Django 3.1.3 on 2021-02-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0020_participant_is_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="is_group",
        ),
    ]
