# Generated by Django 3.1.3 on 2021-02-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0021_remove_participant_is_group"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="place",
            unique_together={("participant",)},
        ),
        migrations.AlterIndexTogether(
            name="place",
            index_together={("participant",)},
        ),
        migrations.RemoveField(
            model_name="place",
            name="exam",
        ),
    ]
