# Generated by Django 3.1.3 on 2021-02-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0022_auto_20210221_1759"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participantsubmission",
            unique_together={("participant", "language")},
        ),
        migrations.AlterIndexTogether(
            name="participantsubmission",
            index_together={("participant", "language")},
        ),
        migrations.RemoveField(
            model_name="participantsubmission",
            name="exam",
        ),
    ]
