# Generated by Django 3.1.3 on 2021-02-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0023_auto_20210221_1823"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("participant", "position")},
        ),
        migrations.AlterIndexTogether(
            name="document",
            index_together={("participant", "position")},
        ),
        migrations.RemoveField(
            model_name="document",
            name="exam",
        ),
    ]
