# Generated by Django 3.1.3 on 2021-02-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0024_auto_20210221_1847"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={"ordering": ["code", "exam"]},
        ),
    ]
