# Generated by Django 3.2.8 on 2021-10-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0017_auto_20210612_2203"),
        ("ipho_exam", "0025_auto_20210222_0034"),
    ]

    operations = []
