# Generated by Django 3.2.8 on 2021-11-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0027_auto_20211129_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='flags',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='flags',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
