# Generated by Django 3.2.10 on 2021-12-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0028_auto_20211129_1959"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="part_position",
            field=models.IntegerField(default=0),
        ),
    ]
