# Generated by Django 3.2.13 on 2022-07-07 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0007_auto_20211130_0251"),
        ("ipho_exam", "0029_feedback_part_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "delegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_core.delegation",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_exam.feedback",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
