# Generated by Django 3.2.14 on 2022-07-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0029_feedback_part_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedHTMLDiff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField()),
                ("target_text", models.TextField()),
                ("diff_text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "timing",
                    models.IntegerField(
                        default=0, help_text="execution time of the diff in ms"
                    ),
                ),
                ("hits", models.IntegerField(default=1)),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_diff_source",
                        to="ipho_exam.versionnode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_diff_target",
                        to="ipho_exam.versionnode",
                    ),
                ),
            ],
            options={
                "ordering": ["-hits", "-timestamp"],
            },
        ),
    ]
