# Generated by Django 4.1.8 on 2023-07-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0033_alter_language_polyglossia'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='can_publish',
            field=models.IntegerField(choices=[(-1, 'Nobody'), (0, 'Organizers')], default=0, help_text='Sets the ability to publish new versions of the exam for organizers.', verbose_name='Can Publish'),
        ),
        migrations.AddField(
            model_name='exam',
            name='can_submit',
            field=models.IntegerField(choices=[(-1, 'No'), (1, 'Yes')], default=-1, help_text='Sets the ability to do a final submission for delegations.', verbose_name='Can Submit'),
        ),
    ]
