# Generated by Django 4.1.10 on 2023-08-12 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipho_exam", "0035_add_min_max_points_in_exam_qml"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["code", "name"]},
        ),
    ]
