# Generated by Django 4.1.10 on 2023-08-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0035_alter_exam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position', 'type', 'code', 'name']},
        ),
    ]
