# Generated by Django 4.1.10 on 2023-09-29 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipho_exam", "0036_alter_exam_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["participant", "position"]},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"ordering": ["delegation", "name"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["exam", "position", "type", "code"]},
        ),
        migrations.AlterModelOptions(
            name="translationnode",
            options={"ordering": ["question", "language", "-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="versionnode",
            options={"ordering": ["question", "language", "-version", "-timestamp"]},
        ),
    ]
