# Generated by Django 4.1.12 on 2024-07-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0037_alter_document_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='has_solution',
            field=models.BooleanField(default=False),
        ),
    ]
