# Generated by Django 4.1.12 on 2024-05-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0038_exam_has_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='topic',
            field=models.CharField(choices=[('T', 'Typo'), ('F', 'Formulation'), ('C', 'Science'), ('S', 'Structure'), ('O', 'Other')], default='O', max_length=1),
            preserve_default=False,
        ),
    ]
