# Generated by Django 4.1.12 on 2024-05-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0039_feedback_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='topic',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='question',
            name='feedback_status',
            field=models.IntegerField(choices=[(2, 'Open'), (1, 'Feedbback entry closed, Everybody can comment, like & withdraw.'), (0, 'Feedbback entry closed, Organizer can comment.'), (-1, 'Feedbback entry closed')], default=-1, help_text='Sets the status of the feedbacks for this questions.', verbose_name='Feedback'),
        ),
    ]
