# Generated by Django 4.1.12 on 2024-06-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0040_rename_topic_feedback_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionnode',
            name='ids_in_order',
            field=models.TextField(default=''),
        ),
    ]
