# Generated by Django 4.1.12 on 2024-06-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0041_versionnode_ids_in_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
