# Generated by Django 4.1.12 on 2025-04-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0036_alter_question_options"),
        ("ipho_exam", "0043_alter_figure_fig_id"),
    ]

    operations = []
