# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import ipho_exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0085_auto_20170319_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='barcode_base',
            field=models.TextField(help_text=b'Common base barcode on all pages'),
        ),
        migrations.AlterField(
            model_name='document',
            name='barcode_num_pages',
            field=models.IntegerField(default=0, help_text=b'Number of pages with a barcode'),
        ),
        migrations.AlterField(
            model_name='document',
            name='exam',
            field=models.ForeignKey(help_text=b'Exam', to='ipho_exam.Exam'),
        ),
        migrations.AlterField(
            model_name='document',
            name='extra_num_pages',
            field=models.IntegerField(default=0, help_text=b'Number of additional pages with barcode (not in the handouts)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text=b'Exam handouts', upload_to=ipho_exam.models.exam_prints_filename, blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='num_pages',
            field=models.IntegerField(default=0, help_text=b'Number of pages of the handouts'),
        ),
        migrations.AlterField(
            model_name='document',
            name='position',
            field=models.IntegerField(help_text=b'Question grouping position, e.g. 0 for cover sheet / instructions, 1 for the first question, etc'),
        ),
        migrations.AlterField(
            model_name='document',
            name='scan_file',
            field=models.FileField(help_text=b'Scanned results. The file is show to the delegation and, if possible, it will contain only the pages with barcode.', upload_to=ipho_exam.models.exam_scans_filename, blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='scan_file_orig',
            field=models.FileField(help_text=b'Original scanned document without page extractions', upload_to=ipho_exam.models.exam_scans_orig_filename, blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='scan_msg',
            field=models.TextField(help_text=b'Warning messages generated by the barcode extractor', null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='scan_status',
            field=models.CharField(blank=True, max_length=10, null=True, help_text=b'Status of the scanned document. S - Success, W - Warning, M - Missing pages', choices=[(b'S', b'Success'), (b'W', b'Warning'), (b'M', b'Missing pages')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(help_text=b'Student', to='ipho_core.Student'),
        ),
    ]
