image: docker:latest
services:
    - docker:dind

stages:
    - build
    - test

variables:
    PROJ_REG: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/master-test
    GIT_DEPTH: 2  # (default=50) we need the previous commit for pre-commit

workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        - if: '$CI_PIPELINE_SOURCE == "push"'


before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

include:
    - local: ".gitlab/ci/build.gitlab-ci.yml"
    # - local: ".gitlab/all.gitlab-ci.yml"
