repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
    name: check-yaml  - check yaml syntax
    exclude: '^(docs/)|(bower_postinstall/)|(static/)|(templates/)|(scripts/)'
  - id: end-of-file-fixer
    name: eof-fixer   - fix end of files
    exclude: '^(docs/)|(bower_postinstall/)|(static/)|(templates/)|(scripts/)'
  - id: trailing-whitespace
    name: trailing-ws - trim trailing whitespace
    exclude: '^(docs/)|(bower_postinstall/)|(static/)|(templates/)|(scripts/)'

- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
  - id: pyupgrade
    name: pyupgrade   - replaces old language syntax to modern version
    args: [--py310-plus]

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    name: black       - code formatter without configuration
    exclude: '/migrations/'
    additional_dependencies: ["click<8.1.0"] # workaround for '_unicodefun' problem: https://github.com/psf/black/issues/2964

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      name: isort       - normalize the order of imports

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.782
#   hooks:
#   - id: mypy
#     name: mypy    - static type analysis
#     exclude: '^(doc/)|(examples/)|(playground/)'

# - repo: local
#   hooks:
#   - id: pylint
#     name: pylint      - python style enforcer
#     entry: poetry run pylint
#     language: system
#     types: [python]
#     exclude: '^(doc/)|(examples/)|(playground/)|(scripts/)'

-   repo: https://github.com/python-poetry/poetry
    rev: "2.1.2"
    hooks:
    - id: poetry-lock
    - id: poetry-check
      args: ["--strict"]
-   repo: https://github.com/python-poetry/poetry-plugin-export
    rev: "1.9.0"
    hooks:
    - id: poetry-export
      args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
    - id: poetry-export
      args: ["--without-hashes", "--only", "dev", "-f", "requirements.txt", "-o", "requirements_dev.txt"]
    - id: poetry-export
      args: ["--without-hashes", "--only", "test", "-f", "requirements.txt", "-o", "requirements_test.txt"]
