repos:
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.20.2
  hooks:
  - id: yapf
    language: system
    exclude: '(migrations/)'

- repo: git://github.com/guykisel/prospector-mirror
  rev: b27f281eb9398fc8504415d7fbdabf119ea8c5e1
  hooks:
  - id: prospector
    language: system
    exclude: '(migrations/)'
