fail_fast: true
repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.2
  hooks:
  - id: pyupgrade
    name: pyupgrade - replaces old language syntax to modern version
    args: [--py38-plus]

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    name: black     - code formatter without configuration

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.782
#   hooks:
#   - id: mypy
#     name: mypy    - static type analysis
#     exclude: '^(doc/)|(examples/)|(playground/)'

- repo: local
  hooks:
  - id: pylint
    name: pylint    - python style enforcer
    entry: pylint
    language: system
    types: [python]
    exclude: '^(doc/)|(examples/)|(playground/)|(scripts/)'
