site_name: Exam Tools Documentation
theme: readthedocs
copyright: Copyright 2014 - 2018, Oly Exams Team
site_dir: _docs_html
pages:
  - "Home": index.md
  - Exam translation:
    - "Step-by-step guide": step_by_step.md
    - "Language settings": language_settings.md
    - "Translations":
      - "My translations": translations.md
      - "Exam editor": exam_editor.md
      - "Exam editor - FAQ": exam_editor_faq.md
    - "Assign exams and submit": assign_exams.md
    - "Exam feedbacks": exam_feedbacks.md
  - "Tool feedbacks": tool_feedbacks.md
  - Administration:
    # - admin_boardmeetings.md
    # - admin_voting_tool.md
    - admin_exam_management.md
    - admin_exam_editor.md
    - admin_figure_management.md
