version: "3.2"
services:
    pre_commit:
        build:
            context: ../
            dockerfile: docker/pre_commit/Dockerfile${VARIANT:-}
            cache_from:
                - pre_commit
        image: pre_commit${VARIANT:-}
        container_name: pre_commit
        volumes:
            - ../:/home/container/workdir:rw
        working_dir: /home/container/workdir
        command: ${PRE_COMMIT_COMMAND:-}
