version: "3.2"
services:
    pre_commit:
        build:
            context: ../../
            dockerfile: docker/pre_commit/Dockerfile
            cache_from:
                - pre_commit
        image: pre_commit
        container_name: pre_commit
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        volumes:
            - ../../:/home/container/workdir:rw
        working_dir: /home/container/workdir
        command: ${PRE_COMMIT_COMMAND:-}
