version: "3.2"
services:
    pre_commit:
        build:
            context: ../../
            dockerfile: docker/pre-commit/Dockerfile
            cache_from:
                - pre-commit
        image: pre-commit
        container_name: pre-commit
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        volumes:
            - ../../:/home/container/workdir:rw
        working_dir: /home/container/workdir
        command: ${PRE_COMMIT_COMMAND:-}
