# Generated by Django 3.1.2 on 2020-10-30 10:56

from django.db import migrations, models
import django.db.models.deletion
import ipho_exam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ipho_exam", "0002_auto_20201027_1229"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "before_switching",
                    models.TextField(
                        blank=True,
                        help_text="Text displayed when confirming switching to this state.",
                        null=True,
                    ),
                ),
                (
                    "available_to_organizers",
                    models.BooleanField(
                        default=True,
                        help_text="Let's the organizers see and select this state",
                    ),
                ),
                (
                    "exam_settings",
                    models.JSONField(
                        default=ipho_exam.models.Exam.get_default_control_settings,
                        help_text="A dictionnary containing fields and settings.",
                    ),
                ),
                (
                    "available_question_settings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of question fields.",
                        null=True,
                    ),
                ),
                (
                    "checks_warning",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of checks which can trigger a warnign when applying the transition.",
                        null=True,
                    ),
                ),
                (
                    "checks_error",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of checks which can prevent the transition.",
                        null=True,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ipho_exam.exam"
                    ),
                ),
            ],
            options={
                "ordering": ["exam", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="examstate",
            constraint=models.UniqueConstraint(
                fields=("exam", "name"), name="Unique name"
            ),
        ),
        migrations.AddConstraint(
            model_name="examstate",
            constraint=models.UniqueConstraint(
                fields=("exam", "position"), name="Unique position"
            ),
        ),
        migrations.AddConstraint(
            model_name="examstate",
            constraint=models.UniqueConstraint(
                fields=("exam", "exam_settings"), name="Unique state"
            ),
        ),
    ]
