# Generated by Django 3.1.3 on 2020-11-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_control", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examphase",
            name="available_to_organizers",
            field=models.BooleanField(
                default=True,
                help_text='Lets organizers with the "can_access_control" permission see and select this phase.',
            ),
        ),
    ]
