# Generated by Django 3.1.2 on 2020-10-30 14:07

from django.db import migrations, models
import django.db.models.deletion
import ipho_exam.models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0002_auto_20201027_1229"),
        ("ipho_control", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="Some superuser", max_length=200)),
                (
                    "to_settings",
                    models.JSONField(
                        default=ipho_exam.models.Exam.get_default_control_settings,
                        help_text="The settings to which the exam was changed.",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ipho_exam.exam"
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        blank=True,
                        help_text="The state to which the exam was changed (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_control.examstate",
                    ),
                ),
            ],
        ),
    ]
