# Generated by Django 3.1.2 on 2020-10-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examstate',
            name='Unique state',
        ),
        migrations.RenameField(
            model_name='examstate',
            old_name='settings',
            new_name='exam_settings',
        ),
        migrations.AlterField(
            model_name='examstate',
            name='available_question_settings',
            field=models.JSONField(blank=True, default=list, help_text='A list of question fields.', null=True),
        ),
        migrations.AddConstraint(
            model_name='examstate',
            constraint=models.UniqueConstraint(fields=('exam', 'exam_settings'), name='Unique state'),
        ),
    ]
