# Generated by Django 3.1.2 on 2020-10-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0002_auto_20201027_1229"),
        ("ipho_control", "0002_examhistory"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExamHistory",
            new_name="ExamControlHistory",
        ),
        migrations.RenameModel(
            old_name="ExamState",
            new_name="ExamControlState",
        ),
        migrations.AlterModelOptions(
            name="examcontrolhistory",
            options={"verbose_name_plural": "exam histories"},
        ),
    ]
