# Generated by Django 3.1.2 on 2020-10-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_control', '0002_auto_20201029_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstate',
            name='before_switching',
            field=models.TextField(blank=True, help_text='Text displayed when confirming switching to this state.', null=True),
        ),
    ]
