# Generated by Django 3.1.3 on 2020-11-03 16:34

from django.db import migrations, models

import ipho_exam.models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_control", "0002_auto_20201103_1608"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examphase",
            name="checks_error",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of checks that can prevent the transition.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="examphase",
            name="checks_warning",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of checks that can trigger a warning when applying the transition.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="examphase",
            name="exam_settings",
            field=models.JSONField(
                default=ipho_exam.models.Exam.get_default_control_settings,
                help_text="A dictionary containing fields and settings.",
            ),
        ),
        migrations.AlterField(
            model_name="examphase",
            name="public_description",
            field=models.TextField(
                help_text="A description shown to all leaders and staff members."
            ),
        ),
    ]
