# Generated by Django 3.1.2 on 2020-11-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_control", "0003_auto_20201030_2200"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examcontrolhistory",
            options={
                "ordering": ["-timestamp"],
                "verbose_name_plural": "exam histories",
            },
        ),
        migrations.AddField(
            model_name="examcontrolstate",
            name="public_description",
            field=models.TextField(
                default=" ",
                help_text="A description that is shown to all leaders and staff members.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="examcontrolstate",
            name="description",
            field=models.TextField(help_text="A description shown to the organizers."),
        ),
    ]
