# Generated by Django 3.1.3 on 2020-11-03 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_control", "0003_auto_20201103_1734"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examphasehistory",
            name="to_phase",
            field=models.ForeignKey(
                blank=True,
                help_text="The phase to which the exam was changed (if applicable).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ipho_control.examphase",
            ),
        ),
    ]
