# Generated by Django 3.2.8 on 2021-11-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_control", "0004_auto_20201103_2102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examphase",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="examphasehistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
