# Generated by Django 3.1.2 on 2020-11-02 20:34

from django.db import migrations, models
import django.db.models.deletion
import ipho_exam.models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0002_auto_20201027_1229"),
        ("ipho_control", "0004_auto_20201101_2329"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamPhase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="A description shown to the organizers."
                    ),
                ),
                (
                    "public_description",
                    models.TextField(
                        help_text="A description that is shown to all leaders and staff members."
                    ),
                ),
                (
                    "before_switching",
                    models.TextField(
                        blank=True,
                        help_text="Text displayed when confirming switching to this phase.",
                        null=True,
                    ),
                ),
                (
                    "available_to_organizers",
                    models.BooleanField(
                        default=True,
                        help_text="Let's the organizers see and select this phase",
                    ),
                ),
                (
                    "exam_settings",
                    models.JSONField(
                        default=ipho_exam.models.Exam.get_default_control_settings,
                        help_text="A dictionnary containing fields and settings.",
                    ),
                ),
                (
                    "available_question_settings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of question fields.",
                        null=True,
                    ),
                ),
                (
                    "checks_warning",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of checks which can trigger a warnign when applying the transition.",
                        null=True,
                    ),
                ),
                (
                    "checks_error",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of checks which can prevent the transition.",
                        null=True,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ipho_exam.exam"
                    ),
                ),
            ],
            options={
                "ordering": ["exam", "position"],
            },
        ),
        migrations.CreateModel(
            name="ExamPhaseHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="Some superuser", max_length=200)),
                (
                    "to_settings",
                    models.JSONField(
                        default=ipho_exam.models.Exam.get_default_control_settings,
                        help_text="The settings to which the exam was changed.",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ipho_exam.exam"
                    ),
                ),
                (
                    "to_phase",
                    models.ForeignKey(
                        blank=True,
                        help_text="The phase to which the exam was changed (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_control.examphase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "exam histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RemoveField(
            model_name="examcontrolstate",
            name="exam",
        ),
        migrations.DeleteModel(
            name="ExamControlHistory",
        ),
        migrations.DeleteModel(
            name="ExamControlState",
        ),
        migrations.AddConstraint(
            model_name="examphase",
            constraint=models.UniqueConstraint(
                fields=("exam", "name"), name="Unique name"
            ),
        ),
        migrations.AddConstraint(
            model_name="examphase",
            constraint=models.UniqueConstraint(
                fields=("exam", "position"), name="Unique position"
            ),
        ),
        migrations.AddConstraint(
            model_name="examphase",
            constraint=models.UniqueConstraint(
                fields=("exam", "exam_settings"), name="Unique phase"
            ),
        ),
    ]
