ARG SERVER_IMG=server

FROM $SERVER_IMG

RUN apt-get update && apt-get install -y \
  libgtk2.0-0 \
  libgtk-3-0 \
  libgbm-dev \
  libnotify-dev \
  libgconf-2-4 \
  libnss3 \
  libxss1 \
  libasound2 \
  libxtst6 \
  xauth \
  xvfb \
  --no-install-recommends && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN  npm -g install cypress --unsafe-perm=true --allow-root --save-dev cypress \
&& cypress install --force

RUN ["mkdir", "-p", "cypress/screenshots", "cypress/videos reports"]

RUN ["chmod", "+x", "./cypress_helper.sh"]

CMD ./cypress_helper.sh
