# Generated by Django 1.11.29 on 2020-10-23 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# ipho_marking.migrations.0002_auto_20200708_2041


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="Marking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "version",
                    models.CharField(
                        choices=[
                            ("O", "Organizers"),
                            ("D", "Delegation"),
                            ("F", "Final"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarkingMeta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("max_points", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=10, help_text="Sorting index inside one question"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_exam.Question",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="marking",
            name="marking_meta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ipho_marking.MarkingMeta",
            ),
        ),
        migrations.AddField(
            model_name="marking",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ipho_core.Student"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="markingmeta",
            unique_together={("question", "name")},
        ),
        migrations.AlterIndexTogether(
            name="markingmeta",
            index_together={("question", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="marking",
            unique_together={("marking_meta", "student", "version")},
        ),
        migrations.CreateModel(
            name="MarkingAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "In progress"),
                            (1, "Submitted"),
                            (2, "Locked"),
                            (3, "Final"),
                        ],
                        default=0,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "delegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marking_status",
                        to="ipho_core.Delegation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_exam.Question",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="markingaction",
            unique_together={("question", "delegation")},
        ),
        migrations.AlterIndexTogether(
            name="markingaction",
            index_together={("question", "delegation")},
        ),
    ]
