# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 20:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipho_core', '0001_initial'),
        ('ipho_exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('version', models.CharField(choices=[('O', 'Organizers'), ('D', 'Delegation'), ('F', 'Final')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MarkingMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('position', models.PositiveSmallIntegerField(default=10, help_text='Sorting index inside one question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipho_exam.Question')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='marking',
            name='marking_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipho_marking.MarkingMeta'),
        ),
        migrations.AddField(
            model_name='marking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipho_core.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='markingmeta',
            unique_together=set([('question', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='markingmeta',
            index_together=set([('question', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='marking',
            unique_together=set([('marking_meta', 'student', 'version')]),
        ),
    ]
