# Generated by Django 1.11.29 on 2020-07-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0002_auto_20190406_1503"),
        ("ipho_core", "0001_initial"),
        ("ipho_marking", "0001_initial"),
    ]

    def forwards(apps, schema_editor):
        MarkingAction = apps.get_model("ipho_marking", "MarkingAction")
        ExamAction = apps.get_model("ipho_exam", "ExamAction")
        if hasattr(ExamAction, "action"):
            for action in ExamAction.objects.filter(action="P").all():
                if action.status == "O":
                    for question in action.exam.question_set.filter(type=1).all():
                        MarkingAction(
                            delegation=action.delegation, question=question, status=0
                        ).save()
                else:
                    for question in action.exam.question_set.filter(type=1).all():
                        MarkingAction(
                            delegation=action.delegation, question=question, status=1
                        ).save()
        return

    def backwards(apps, schema_editor):
        MarkingAction = apps.get_model("ipho_marking", "MarkingAction")
        ExamAction = apps.get_model("ipho_exam", "ExamAction")
        if hasattr(ExamAction, "action"):
            for action in MarkingAction.objects.all():
                eact, _ = ExamAction.objects.get_or_create(
                    delegation=action.delegation, exam=action.question.exam, action="P"
                )
                if MarkingAction.objects.filter(
                    delegation=action.delegation,
                    question__exam=action.question.exam,
                    status=0,
                ).exists():
                    eact.status = "O"
                else:
                    eact.status = "S"
                eact.save()
        return

    operations = [
        migrations.CreateModel(
            name="MarkingAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "In progress"),
                            (1, "Submitted"),
                            (2, "Locked"),
                            (3, "Final"),
                        ],
                        default=0,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "delegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marking_status",
                        to="ipho_core.Delegation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_exam.Question",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="markingaction",
            unique_together={("question", "delegation")},
        ),
        migrations.AlterIndexTogether(
            name="markingaction",
            index_together={("question", "delegation")},
        ),
        migrations.RunPython(forwards, backwards),
    ]
