# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0002_auto_20190406_1503'),
        ('ipho_core', '0001_initial'),
        ('ipho_marking', '0001_initial'),
    ]

    def forwards(apps, schema_editor):
        #MarkingAction = apps.get_model("ipho_marking","MarkingAction")
        from ipho_marking.models import MarkingAction
        from ipho_exam.models import ExamAction
        if hasattr(ExamAction, 'POINTS'):
            for action in ExamAction.objects.filter(action=ExamAction.POINTS).all():
                if action.status == ExamAction.OPEN:
                    for question in action.exam.question_set.all():
                        MarkingAction(delegation=action.delegation, question=question, status=MarkingAction.OPEN).save()
                else:
                    for question in action.exam.question_set.all():
                        MarkingAction(delegation=action.delegation, question=question, status=MarkingAction.SUBMITTED).save()
        return

    def backwards(apps, schema_editor):
        from ipho_marking.models import MarkingAction
        from ipho_exam.models import ExamAction
        if hasattr(ExamAction, 'POINTS'):
            for action in MarkingAction.objects.all():
                eact, _ = ExamAction.objects.get_or_create(delegation=action.delegation, exam=action.question.exam, action=ExamAction.POINTS)
                if MarkingAction.objects.filter(delegation=action.delegation, question__exam=action.question.exam, status=MarkingAction.OPEN).exists():
                    eact.status = ExamAction.OPEN
                else:
                    eact.status = ExamAction.SUBMITTED
                eact.save()
        return

    operations = [
        migrations.CreateModel(
            name='MarkingAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (1, 'Submitted'), (2, 'Locked'), (3, 'Final')], default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_status', to='ipho_core.Delegation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipho_exam.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='markingaction',
            unique_together=set([('question', 'delegation')]),
        ),
        migrations.AlterIndexTogether(
            name='markingaction',
            index_together=set([('question', 'delegation')]),
        ),
        migrations.RunPython(forwards, backwards),
    ]
