# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0002_auto_20190406_1503'),
        ('ipho_core', '0001_initial'),
        ('ipho_marking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (1, 'Submitted'), (2, 'Locked'), (3, 'Final')], default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_status', to='ipho_core.Delegation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipho_exam.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='markingaction',
            unique_together=set([('question', 'delegation')]),
        ),
        migrations.AlterIndexTogether(
            name='markingaction',
            index_together=set([('question', 'delegation')]),
        ),
    ]
