# Generated by Django 3.1.3 on 2021-02-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0007_auto_20210208_2247"),
        ("ipho_marking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marking",
            old_name="student",
            new_name="participant",
        ),
        migrations.AlterUniqueTogether(
            name="marking",
            unique_together={("marking_meta", "participant", "version")},
        ),
    ]
