# Generated by Django 3.1.3 on 2021-02-18 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0016_auto_20210218_1233"),
        ("ipho_marking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marking",
            name="participant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="ipho_exam.participant",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="marking",
            unique_together={("marking_meta", "participant", "version")},
        ),
        migrations.RemoveField(
            model_name="marking",
            name="student",
        ),
    ]
