# Generated by Django 3.1.3 on 2021-02-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0018_auto_20210218_1159"),
        ("ipho_marking", "0002_auto_20210208_2315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marking",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ipho_exam.participant"
            ),
        ),
    ]
