# Generated by Django 3.2.10 on 2021-12-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_marking", "0003_auto_20211130_0251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marking",
            name="points",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
