# Generated by Django 4.1.10 on 2023-09-29 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipho_marking", "0005_questionpointsrescale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marking",
            options={"ordering": ["marking_meta", "participant", "version"]},
        ),
        migrations.AlterModelOptions(
            name="markingaction",
            options={"ordering": ["question", "delegation"]},
        ),
        migrations.AlterModelOptions(
            name="markingmeta",
            options={"ordering": ["question", "position"]},
        ),
    ]
