# Generated by Django 4.1.10 on 2023-07-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_marking', '0005_questionpointsrescale'),
        ('ipho_exam', '0035_add_min_max_points_in_exam_qml'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingmeta',
            name='min_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='markingmeta',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
