# Generated by Django 4.1.8 on 2023-07-22 20:05

from django.db import migrations, models

import ipho_marking.models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_marking', '0006_markingmeta_min_points_alter_markingmeta_max_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpointsrescale',
            name='max_external_points',
        ),
        migrations.RemoveField(
            model_name='questionpointsrescale',
            name='max_internal_points',
        ),
        migrations.AddField(
            model_name='questionpointsrescale',
            name='denominator',
            field=models.PositiveSmallIntegerField(default=1, validators=[ipho_marking.models.validate_nonzero]),
        ),
        migrations.AddField(
            model_name='questionpointsrescale',
            name='numerator',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionpointsrescale',
            name='shift',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
