include:
  - path:
      - docker-compose-common.yml

services:
  django-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: django-server-dbg
    env_file:
      # TODO: maybe move parts of these into Dockerfile?
      - env/secret_locations.env
      - env/common.env
      - env/a-dev.env
    command: /bin/sh -c "python docker/wait_for/wait_for_postgres_60.py && python manage.py migrate && python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    ports:
      - "${DJANGO_PORT:-8000}:8000"
      - "${DEBUGPY_PORT:-5678}:5678"
    volumes:
      - secrets:/run/secrets:ro
      - ../:/home/container/workdir:rw
  celery-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: celery-worker-nosrc
    env_file:
      # TODO: maybe move parts of these into Dockerfile?
      - env/secret_locations.env
      - env/common.env
      - env/a-dev.env
    volumes:
      - secrets:/run/secrets:ro
      - ../:/home/container/workdir:rw
