FROM $CONTAINER_TEST_IMAGE

RUN exec mkdir -p app/cypress/screenshots app/cypress/videos


RUN cd /app && exec npx cypress verify && exec chmod +x cypress_helper.sh

ENTRYPOINT ["./cypress_helper.sh"]
