version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.master
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbit
  worker:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.worker
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbit
  rabbit:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"

volumes:
  dbdata: {}
