# Generated by Django 3.1.2 on 2020-11-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iphoperm",
            options={
                "permissions": (
                    ("is_delegation", "Is a delegation"),
                    ("is_delegation_print", "Is in the print team of a delegation"),
                    ("is_marker", "Is a marker"),
                    ("can_vote", "Can vote"),
                    (
                        "can_see_boardmeeting",
                        "Can see the exam, feedbacks, and votes when they are available to delegations",
                    ),
                    ("is_organizer", "Is an organizer"),
                    ("can_impersonate", "Can impersonate delegations"),
                    ("can_access_control", "Can access the control app"),
                    ("print_technopark", "Can print in Technopark"),
                    ("print_irchel", "Can print in Irchel"),
                    ("is_printstaff", "Is a print staff"),
                )
            },
        ),
        migrations.AlterField(
            model_name="delegation",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
