# Generated by Django 1.11.20 on 2019-07-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegation",
            name="auto_translate_char_count",
            field=models.IntegerField(default=0),
        ),
    ]
