# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-04 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iphoperm',
            options={'permissions': (('is_delegation', 'Is a delegation'), ('is_delegation_print', 'Is in the print team of a delegation'), ('is_marker', 'Is a marker'), ('can_vote', 'Can vote'), ('is_staff', 'Is an organizer'), ('can_impersonate', 'Can impersonate delegations'), ('print_technopark', 'Can print in Technopark'), ('print_irchel', 'Can print in Irchel'), ('is_printstaff', 'Is a print staff'))},
        ),
    ]
