# Generated by Django 3.1.2 on 2020-11-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegation",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
