# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_core', '0002_delegation_auto_translate_char_count'),
        ('ipho_core', '0002_auto_20200704_2212'),
    ]

    operations = [
    ]
