# Generated by Django 1.11.29 on 2020-07-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0003_merge_20200713_1017"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iphoperm",
            options={
                "permissions": (
                    ("is_delegation", "Is a delegation"),
                    ("is_delegation_print", "Is in the print team of a delegation"),
                    ("is_marker", "Is a marker"),
                    ("can_vote", "Can vote"),
                    (
                        "can_see_boardmeeting",
                        "Can see the exam, feedbacks, and votes when they are available to delegations",
                    ),
                    ("is_staff", "Is an organizer"),
                    ("can_impersonate", "Can impersonate delegations"),
                    ("print_technopark", "Can print in Technopark"),
                    ("print_irchel", "Can print in Irchel"),
                    ("is_printstaff", "Is a print staff"),
                )
            },
        ),
    ]
