# Generated by Django 3.1.3 on 2020-11-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0004_auto_20201111_1925"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iphoperm",
            options={
                "permissions": (
                    ("is_delegation", "Is a delegation"),
                    ("is_delegation_print", "Is in the print team of a delegation"),
                    ("is_marker", "Is a marker"),
                    ("can_edit_exam", "Can edit the exam"),
                    ("can_manage_feedback", "Can manage feedbacks"),
                    ("can_manage_poll", "Can manage polls"),
                    ("can_vote", "Can vote"),
                    (
                        "can_see_boardmeeting",
                        "Can see the exam, feedbacks, and votes when they are available to delegations",
                    ),
                    ("is_organizer_admin", "Is an organizer admin"),
                    ("can_impersonate", "Can impersonate delegations"),
                    ("can_access_control", "Can access the control app"),
                    ("print_boardmeeting_site", "Can print at the boardmeeting site"),
                    ("print_exam_site", "Can print at the exam site"),
                    ("is_printstaff", "Is a print staff"),
                )
            },
        ),
    ]
