# Generated by Django 3.1.3 on 2021-02-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_marking", "0001_initial"),
        ("ipho_exam", "0015_auto_20201119_1911"),
        ("ipho_core", "0006_auto_20201123_2133"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student",
            new_name="Participant",
        ),
    ]
