# Generated by Django 3.1.3 on 2021-02-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0007_auto_20210208_2247"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Participant",
            new_name="Student",
        ),
    ]
