# Generated by Django 4.1.12 on 2024-04-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_core", "0007_auto_20211130_0251"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AutoLogin",
        ),
    ]
