# Generated by Django 1.11.20 on 2019-03-26 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ipho_exam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=3, null=True)),
                ("choice_text", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date published"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end date"
                    ),
                ),
                (
                    "vote_result",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "In progress"), (1, "Rejected"), (2, "Accepted")],
                        default=0,
                    ),
                ),
                (
                    "implementation",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Not implemented"), (1, "Implemented")], default=0
                    ),
                ),
                (
                    "feedbacks",
                    models.ManyToManyField(
                        blank=True, related_name="vote", to="ipho_exam.Feedback"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_poll.Choice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipho_poll.Question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VotingRight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vote",
            name="voting_right",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ipho_poll.VotingRight"
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ipho_poll.Question"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("question", "voting_right")},
        ),
    ]
