# Generated by Django 3.1.3 on 2020-12-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_poll", "0002_votingroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="voting_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ipho_poll.votingroom",
            ),
        ),
    ]
