# Generated by Django 3.1.3 on 2020-12-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_poll", "0004_votingroom_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingroom",
            name="visibility",
            field=models.IntegerField(
                choices=[
                    (-1, "2nd level support only"),
                    (0, "Organizer + 2nd level support"),
                    (1, "Boardmeeting + Organizer + 2nd level support"),
                ],
                default=1,
                help_text="Sets the visibility of the voting room for organizers and delegations.",
                verbose_name="Voting Room Visibility",
            ),
        ),
    ]
