# Generated by Django 3.1.3 on 2020-12-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_poll", "0006_auto_20201216_1738"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choice",
            new_name="VotingChoice",
        ),
    ]
