# Generated by Django 3.1.3 on 2020-12-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_poll", "0007_auto_20201216_1849"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vote",
            new_name="CastedVote",
        ),
    ]
