version: "3.2"
services:
    testing_cypress:
        build:
            context: ../../
            dockerfile: docker/testing_cypress/Dockerfile
            cache_from:
                - testing_cypress
        image: testing_cypress
        container_name: testing_cypress
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        volumes:
            - ../../:/home/container/workdir:rw
        working_dir: /home/container/workdir/e2e
        network_mode: host  #will be changed to a docker-network later
