version: "3.2"
services:
    testing_cypress:
        build:
            context: ../
            dockerfile: docker/testing_cypress/Dockerfile${VARIANT:-}
            cache_from:
                - testing_cypress
        image: testing_cypress${VARIANT:-}
        container_name: testing_cypress
        volumes:
            - ../:/home/container/workdir:rw
        working_dir: /home/container/workdir/e2e
        network_mode: host  #will be changed to a docker-network later
