version: "3.2"
# --project-directory=docker, see compose.sh
# therefore we specify relative to the docker folder, not this subfolder
services:
    django-server:
        build:
            context: ../
            dockerfile: docker/django-server/Dockerfile
            cache_from:
                - django-server
        image: django-server
        container_name: django-server
        user: $U_ID:$G_ID
        volumes:
            - ../:/home/container/workdir:rw
            - ./wait-for-it.sh:/tmp/wait-for-it.sh:ro
        working_dir: /home/container/workdir
        ports:
            - 8000:8000
        # expose:
        #     - 8000
        environment:
            - BOWER_STATIC_PATH=${DJANGO_SERVER_BOWER_STATIC_PATH:-/home/container/bower/static}
        command: python manage.py runserver
        healthcheck:
            test: /tmp/wait-for-it.sh localhost:8000 -t 3
            interval: 60s
            timeout: 10s
            retries: 2
