# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipho_exam', '0024_language_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='font',
            field=models.CharField(
                default=b'notosans',
                max_length=100,
                choices=[
                    (b'notokufiarabic', b'Noto Kufi Arabic'), (b'notonaskharabic', b'Noto Naskh Arabic'),
                    (b'notonaskharabicui', b'Noto Naskh Arabic UI'), (b'notonastaliqurdu', b'Noto Nastaliq Urdu'),
                    (b'notonastaliqurdudraft',
                     b'Noto Nastaliq Urdu Draft'), (b'notosans',
                                                    b'Noto Sans'), (b'notosansarmenian', b'Noto Sans Armenian'),
                    (b'notosansavestan',
                     b'Noto Sans Avestan'), (b'notosansbalinese',
                                             b'Noto Sans Balinese'), (b'notosansbamum', b'Noto Sans Bamum'),
                    (b'notosansbatak',
                     b'Noto Sans Batak'), (b'notosansbengali',
                                           b'Noto Sans Bengali'), (b'notosansbengaliui', b'Noto Sans Bengali UI'),
                    (b'notosansbrahmi',
                     b'Noto Sans Brahmi'), (b'notosansbuginese',
                                            b'Noto Sans Buginese'), (b'notosansbuhid', b'Noto Sans Buhid'),
                    (b'notosanscanadianaboriginal',
                     b'Noto Sans Canadian Aboriginal'), (b'notosanscarian',
                                                         b'Noto Sans Carian'), (b'notosanscham', b'Noto Sans Cham'),
                    (b'notosanscherokee',
                     b'Noto Sans Cherokee'), (b'notosanscoptic',
                                              b'Noto Sans Coptic'), (b'notosanscuneiform', b'Noto Sans Cuneiform'),
                    (b'notosanscypriot',
                     b'Noto Sans Cypriot'), (b'notosansdeseret',
                                             b'Noto Sans Deseret'), (b'notosansdevanagari', b'Noto Sans Devanagari'),
                    (b'notosansdevanagariui',
                     b'Noto Sans Devanagari UI'), (b'notosansegyptianhieroglyphs', b'Noto Sans Egyptian Hieroglyphs'),
                    (b'notosansethiopic', b'Noto Sans Ethiopic'), (b'notosansgeorgian', b'Noto Sans Georgian'),
                    (b'notosansgothic',
                     b'Noto Sans Gothic'), (b'notosansgujarati',
                                            b'Noto Sans Gujarati'), (b'notosansgujaratiui', b'Noto Sans Gujarati UI'),
                    (b'notosansgurmukhi',
                     b'Noto Sans Gurmukhi'), (b'notosansgurmukhiui',
                                              b'Noto Sans Gurmukhi UI'), (b'notosanshanunoo', b'Noto Sans Hanunoo'),
                    (b'notosanshebrew',
                     b'Noto Sans Hebrew'), (b'notosansimperialaramaic', b'Noto Sans Imperial Aramaic'),
                    (b'notosansinscriptionalpahlavi', b'Noto Sans Inscriptional Pahlavi'),
                    (b'notosansinscriptionalparthian',
                     b'Noto Sans Inscriptional Parthian'), (b'notosansjapanese', b'Noto Sans Japanese'),
                    (b'notosansjavanese',
                     b'Noto Sans Javanese'), (b'notosansjp', b'Noto Sans JP'), (b'notosanskaithi', b'Noto Sans Kaithi'),
                    (b'notosanskannada', b'Noto Sans Kannada'), (b'notosanskannadaui', b'Noto Sans Kannada UI'),
                    (b'notosanskayahli', b'Noto Sans Kayah Li'), (b'notosanskharoshthi', b'Noto Sans Kharoshthi'),
                    (b'notosanskhmer', b'Noto Sans Khmer'), (b'notosanskhmerui',
                                                             b'Noto Sans Khmer UI'), (b'notosanskr', b'Noto Sans KR'),
                    (b'notosanskufiarabic',
                     b'Noto Sans Kufi Arabic'), (b'notosanslao',
                                                 b'Noto Sans Lao'), (b'notosanslaoui', b'Noto Sans Lao UI'),
                    (b'notosanslepcha',
                     b'Noto Sans Lepcha'), (b'notosanslimbu',
                                            b'Noto Sans Limbu'), (b'notosanslinearb', b'Noto Sans Linear B'),
                    (b'notosanslisu',
                     b'Noto Sans Lisu'), (b'notosanslycian',
                                          b'Noto Sans Lycian'), (b'notosanslydian', b'Noto Sans Lydian'),
                    (b'notosansmalayalam', b'Noto Sans Malayalam'), (b'notosansmalayalamui', b'Noto Sans Malayalam UI'),
                    (b'notosansmandaic', b'Noto Sans Mandaic'), (b'notosansmeeteimayek', b'Noto Sans Meetei Mayek'),
                    (b'notosansmongolian',
                     b'Noto Sans Mongolian'), (b'notosansmyanmar',
                                               b'Noto Sans Myanmar'), (b'notosansmyanmarui', b'Noto Sans Myanmar UI'),
                    (b'notosansnewtailue',
                     b'Noto Sans New Tai Lue'), (b'notosansogham',
                                                 b'Noto Sans Ogham'), (b'notosansolchiki', b'Noto Sans Ol Chiki'),
                    (b'notosansolditalic', b'Noto Sans Old Italic'), (b'notosansoldpersian', b'Noto Sans Old Persian'),
                    (b'notosansoldsoutharabian',
                     b'Noto Sans Old South Arabian'), (b'notosansoldturkic',
                                                       b'Noto Sans Old Turkic'), (b'notosansoriya', b'Noto Sans Oriya'),
                    (b'notosansoriyaui', b'Noto Sans Oriya UI'), (b'notosansosmanya', b'Noto Sans Osmanya'),
                    (b'notosansphagspa',
                     b'Noto Sans Phags Pa'), (b'notosansphoenician',
                                              b'Noto Sans Phoenician'), (b'notosansrejang', b'Noto Sans Rejang'),
                    (b'notosansrunic',
                     b'Noto Sans Runic'), (b'notosanssamaritan',
                                           b'Noto Sans Samaritan'), (b'notosanssaurashtra', b'Noto Sans Saurashtra'),
                    (b'notosanssc',
                     b'Noto Sans SC'), (b'notosansshavian',
                                        b'Noto Sans Shavian'), (b'notosanssinhala', b'Noto Sans Sinhala'),
                    (b'notosanssundanese', b'Noto Sans Sundanese'), (b'notosanssylotinagri', b'Noto Sans Syloti Nagri'),
                    (b'notosanssyriaceastern',
                     b'Noto Sans Syriac Eastern'), (b'notosanssyriacestrangela', b'Noto Sans Syriac Estrangela'),
                    (b'notosanssyriacwestern',
                     b'Noto Sans Syriac Western'), (b'notosanstagalog',
                                                    b'Noto Sans Tagalog'), (b'notosanstagbanwa', b'Noto Sans Tagbanwa'),
                    (b'notosanstaile',
                     b'Noto Sans Tai Le'), (b'notosanstaitham',
                                            b'Noto Sans Tai Tham'), (b'notosanstaiviet', b'Noto Sans Tai Viet'),
                    (b'notosanstamil', b'Noto Sans Tamil'), (b'notosanstamilui',
                                                             b'Noto Sans Tamil UI'), (b'notosanstc', b'Noto Sans TC'),
                    (b'notosanstelugu',
                     b'Noto Sans Telugu'), (b'notosansteluguui',
                                            b'Noto Sans Telugu UI'), (b'notosansthaana', b'Noto Sans Thaana'),
                    (b'notosansthai',
                     b'Noto Sans Thai'), (b'notosansthaiui',
                                          b'Noto Sans Thai UI'), (b'notosanstibetan', b'Noto Sans Tibetan'),
                    (b'notosanstifinagh',
                     b'Noto Sans Tifinagh'), (b'notosansugaritic',
                                              b'Noto Sans Ugaritic'), (b'notosansvai', b'Noto Sans Vai'),
                    (b'notosansyi', b'Noto Sans Yi'), (b'notoserif',
                                                       b'Noto Serif'), (b'notoserifarmenian', b'Noto Serif Armenian'),
                    (b'notoserifgeorgian',
                     b'Noto Serif Georgian'), (b'notoseriflao',
                                               b'Noto Serif Lao'), (b'notoserifthai', b'Noto Serif Thai')
                ]
            ),
        ),
    ]
