# Generated by Django 1.11.20 on 2019-03-09 22:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("ipho_exam", "0097_exam_hide_feedback"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="compiledfigure",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("base_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="rawfigure",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("base_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
