pre-build:oly-python-deps:
    extends: .build:build_cached_push
    stage: "pre-build"
    needs: []
    variables:
        SERVICE_NAME: oly-python-deps
    rules:
        - if: '$DOCKER_CACHE == "no"'
        - if: '$IMG_NAME != $IMG_COMPARE'
        - changes:
            - .gitlab/ci/build.yml
            - requirements.txt

build:django-server:
    extends: .build:build_cached_push
    variables:
        SERVICE_NAME: django-server
        BUILD_DEPENDENCY: oly-python-deps
    rules:
        - if: '$DOCKER_CACHE == "no"'
        - if: '$IMG_NAME != $IMG_COMPARE'
        - changes:
            - .gitlab/ci/build.yml
            - requirements.txt
            - bower/*


build:celery-worker:
    extends: .build:build_cached_push
    variables:
        SERVICE_NAME: celery-worker
        BUILD_DEPENDENCY: oly-python-deps
    rules:
        - if: '$DOCKER_CACHE == "no"'
        - if: '$IMG_NAME != $IMG_COMPARE'
        - changes:
            - .gitlab/ci/build.yml
            - requirements.txt

build:testing-cypress:
    extends: .build:build_cached_push
    variables:
        SERVICE_NAME: testing-cypress
    rules:
        - if: '$DOCKER_CACHE == "no"'
        - if: '$IMG_NAME != $IMG_COMPARE'
        # this dep is not real, but here to trigger the build in a new branch.
        # Theoretically, testing-cypress is branch independent, but to use
        # the same mechanisms we still build it in every branch.
        - changes:
            - .gitlab/ci/build.yml
            - requirements.txt
