image: docker/compose
services:
    - docker:dind

stages:
    - pre-build
    - build
    - test

variables:
    # directories
    ROOT: $CI_BUILDS_DIR/root
    PROJECT_DIR: exam_tools
    DOCKER_DIR: docker_deploy/docker
    DEPLOY_REPO_GROUP: oly-exams
    DEPLOY_REPO_NAME: docker_deploy
    DEPLOY_REPO_BRANCH: icho2022

    # docker related variables
    DOCKER_CACHE: "yes"
    DOCKER_LAYER_CACHE: "yes"
    PROJ_REG: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/master-test"
    # this is an unelegant fact: on push only the first is defined
    # and the second empty "", on merge-request it is the other way.
    # With this concat, we always have a well defined IMG_NAME
    IMG_NAME: "${CI_COMMIT_BRANCH}${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
    # need this to detect if a web request sets a different IMG_NAME
    IMG_COMPARE: "${CI_COMMIT_BRANCH}${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"

    # technical git variables
    GIT_DEPTH: 2  # (default=50) we need the previous commit for pre-commit
    GIT_CLONE_PATH: $CI_BUILDS_DIR/root/exam_tools

workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "web"'
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        - if: '$CI_PIPELINE_SOURCE == "push"'


before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

    - apk update
    - apk add git openssh-client
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/$DEPLOY_REPO_GROUP/$DEPLOY_REPO_NAME.git".insteadOf git@gitlab.com:$DEPLOY_REPO_GROUP/$DEPLOY_REPO_NAME.git
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    # Add gitlab to known_hosts
    - cd $ROOT
    - git clone --depth=1 -b ${DEPLOY_REPO_BRANCH:-master} git@gitlab.com:$DEPLOY_REPO_GROUP/$DEPLOY_REPO_NAME.git
    - git -C $DEPLOY_REPO_NAME rev-parse HEAD
    - "echo Deploy Repo Branch: $DEPLOY_REPO_BRANCH"
    - "echo Root Dir: $ROOT"
    - "echo Pipeline source: $CI_PIPELINE_SOURCE"
    - "echo Image Name: $IMG_NAME"

include:  #relative to project root
    - local: ".gitlab/ci/templates.yml"
    - local: ".gitlab/ci/build.yml"
    - local: ".gitlab/ci/test.yml"
    - local: ".gitlab/ci/merge.yml"
