image: docker/compose:latest
services:
    - docker:dind

stages:
    - build
    - test

variables:
    PROJ_REG: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/master-test"
    GIT_DEPTH: 2  # (default=50) we need the previous commit for pre-commit

    DOCKER_CACHE: "1"
    # this is an unelegant fact: on push only the first is defined
    # and the second empty "", on merge-request it is the other way.
    # With this concat, we always have a well defined IMG_NAME
    IMG_NAME: $CI_COMMIT_BRANCH$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    # need this to detect if a web request sets a different IMG_NAME
    IMG_COMPARE: $CI_COMMIT_BRANCH$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME

workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "web"'
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        - if: '$CI_PIPELINE_SOURCE == "push"'


before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - echo $CI_PIPELINE_SOURCE
    - echo $IMG_NAME

include:  #relative to project root
    - local: ".gitlab/ci/templates.yml"
    - local: ".gitlab/ci/pre-commit.yml"
    - local: ".gitlab/ci/django_server.yml"
