.test:pull_and_run:
    stage: test
    variables:
        IMG_TAG: $CI_COMMIT_BRANCH
    script:
        - IMG="$PROJ_REG/$IMG_NAME:$IMG_TAG"
        - docker pull $IMG
        - docker run -v $PWD:/src:rw,z --workdir /src $IMG
        # z means shared among many, Z is exclusive private mount


test:pre-commit:
    extends: .test:pull_and_run
    variables:
        IMG_NAME: pre-commit


test:cypress:
    extends: .test:pull_and_run
    variables:
        IMG_NAME: server
